api-token: ''
money-symbol: '$'
# How long you have to wait after buying shares of a stock to sell it (seconds)
# 900 = 15 minutes
# 15 minutes is recommended to prevent players from cheating by monitoring other sources
trade-cooldown: 900
whitelist:
  enabled: false
  stocks:
    - AAPL
    - MSFT
    - AMZN
    - NVDA
    - GOOGL
    - GOOG
    - META
    - TSLA
blacklist:
  enabled: false
  stocks: []